/* ============================================================
   BANCO DE PREGUNTAS — SOLO DATOS (intercambiable)
   Contrato: meta (id, titulo, subtitulo, descripcion, nota) ·
             secciones {LETRA:{nombre,color}} ·
             preguntas [{s,q,o[],c,e}]  ·  c = índice correcto
   ============================================================ */
const BANCO={
meta:{
  id:"verbos-regulares-irregulares-v1",
  titulo:"Test de verbos",
  subtitulo:"regulares e irregulares",
  descripcion:"Preguntas de opción múltiple basadas estrictamente en la lista de verbos adjunta: paradigmas irregulares, patrones morfológicos, significados en español y pronunciación de los regulares. Sin conceptos repetidos entre preguntas.",
  nota:"Nota de rigor: el documento original presenta particularidades (show y learn figuran en ambas listas; used clasificado como /t/; plan → planed sin duplicación) que este test respeta al pie de la letra."
},
secciones:{
  A:{nombre:"Paradigmas irregulares",color:"#f5a524"},
  B:{nombre:"Patrones morfológicos",color:"#10b981"},
  C:{nombre:"Significado en español",color:"#38bdf8"},
  D:{nombre:"Verbos regulares",color:"#f472b6"}
},
preguntas:[
{s:"A",q:"¿Cuál de los siguientes verbos presenta exactamente la misma forma en infinitivo, pasado simple y participio pasado?",o:["Bend","Cast","Feel","Keep"],c:1,e:"La lista registra cast → cast → cast ('arrojar'); bend → bent, feel → felt y keep → kept cambian en pasado y participio."},
{s:"A",q:"¿Qué verbo tiene un pasado simple idéntico al infinitivo, pero un participio pasado diferente?",o:["Bet","Cast","Beat","Cut"],c:2,e:"Beat → beat → beaten (golpear): solo el participio añade '-en'; bet, cast y cut repiten las tres formas."},
{s:"A",q:"¿Qué verbo tiene un participio idéntico al infinitivo, pero un pasado simple distinto?",o:["Shut","Set","Put","Overcome"],c:3,e:"Overcome → overcame → overcome (vencer); en shut, set y put las tres formas coinciden, por lo que su pasado no difiere del infinitivo."},
{s:"A",q:"Según la lista, la relación correcta entre 'lie' y 'lay' es:",o:["lie–laid–lain / lay–lay–laid","lie–lied–lain / lay–lay–laid","lie–lay–lain / lay–laid–laid","lie–lay–laid / lay–laid–lain"],c:2,e:"Lie (echarse) forma lay/lain; lay (poner) forma laid/laid; las demás combinaciones cruzan ambas conjugaciones."},
{s:"A",q:"Las formas 'wound / wound' (pasado y participio) corresponden al infinitivo:",o:["Wring","Weave","Wet","Wind"],c:3,e:"Wind → wound → wound = 'enrollar'; wring → wrung, weave → wove/woven, wet invariable."},
{s:"A",q:"El participio pasado de 'stride' es:",o:["Strided","Stridden","Struck","Strung"],c:1,e:"Stride → strode → stridden (dar zancadas); 'struck' pertenece a strike y la lista no registra 'strided' ni 'strung'."},
{s:"A",q:"'Trodden' es participio pasado de:",o:["Thrust","Throw","Tread","Tell"],c:2,e:"Tread → trod → trodden (pisar, hollar); thrust es invariable, throw → thrown, tell → told."},
{s:"A",q:"El pasado simple de 'forbid' es:",o:["Forbode","Forbid","Forbidden","Forbade"],c:3,e:"Forbid → forbade → forbidden (prohibir); 'forbidden' es el participio y 'forbid' el infinitivo."},
{s:"A",q:"¿Qué verbo registra 'swelled' como pasado simple y 'swollen' como participio?",o:["Swell","Spring","Swing","Swim"],c:0,e:"Swell (hinchar) combina pasado de apariencia regular con participio irregular; spring → sprang/sprung, swing → swung, swim → swam/swum."},
{s:"A",q:"'Mistaken' es participio pasado de:",o:["Make","Take","Mistake","Meet"],c:2,e:"Mistake → mistook → mistaken (equivocar); make → made, take → taken, meet → met."},
{s:"A",q:"El participio de 'bear' (soportar, dar a luz) registrado en la lista es:",o:["Bore únicamente","Borne / Born","Beared","Borned"],c:1,e:"Bear → bore → borne/born: uno de los pocos verbos de la lista con participio doble."},
{s:"A",q:"¿Qué verbo admite 'gotten' como variante de participio?",o:["Forget","Wet","Bet","Get"],c:3,e:"Get → got → got/gotten (obtener); forget → forgotten (único) y wet/bet son invariables."},
{s:"A",q:"¿Qué verbo presenta doble pasado simple ('stank/stunk') con participio único?",o:["Stink","Sink","Spring","Shrink"],c:0,e:"Stink (apestar) → stank/stunk → stunk; sink, spring y shrink registran un solo pasado (sank, sprang, shrank)."},
{s:"A",q:"¿Qué par de verbos significa lo mismo ('despertarse') y conjuga en paralelo?",o:["Arise / Rise","Awake / Wake","Come / Become","Go / Do"],c:1,e:"Awake → awoke → awoken y wake → woke → woken; arise (surgir) → arose/arisen ≠ rise → rose/risen; come → came ≠ become → became; go → went ≠ do → did."},
{s:"A",q:"El pasado 'went' es un caso de supleción (no guarda relación formal con su infinitivo). Corresponde a:",o:["Want","Wind","Go","Weep"],c:2,e:"Go (goes) → went → gone (ir); want es regular (wanted /Id/), wind → wound, weep → wept."},
{s:"A",q:"Las formas 'found / found' corresponden al verbo que significa:",o:["Sentir","Volar","Llenar","Encontrar"],c:3,e:"Find → found → found = 'encontrar'; feel → felt, fly → flew/flown, fill → filled (regular /d/)."},
{s:"A",q:"'Left' es pasado y participio de:",o:["Let (permitir)","Leave (dejar)","Lead (conducir)","Lose (perder)"],c:1,e:"Leave → left → left; let es invariable, lead → led, lose → lost."},
{s:"A",q:"'Held' corresponde a:",o:["Hold","Hear","Hurt","Keep"],c:0,e:"Hold (agarrar, celebrar) → held → held; hear → heard, hurt invariable, keep → kept."},
{s:"A",q:"'Hidden' es participio de:",o:["Hold","Hit","Bid","Hide"],c:3,e:"Hide → hid → hidden (ocultar); hit y bid son invariables."},
{s:"A",q:"'Ridden' es participio de:",o:["Rise","Write","Ride","Read"],c:2,e:"Ride → rode → ridden (montar); rise → risen, write → written, read invariable."},
{s:"A",q:"El pasado simple de 'flee' es:",o:["Flew","Fled","Flyed","Flewn"],c:1,e:"Flee → fled → fled (huir); 'flew/flown' pertenecen a fly (volar): confusión clásica."},
{s:"A",q:"El pasado y participio de 'shine' (brillar) es:",o:["Shown","Shined","Shook","Shone"],c:3,e:"Shine → shone → shone; 'shown' es participio de show y 'shook' es pasado de shake."},
{s:"A",q:"¿Qué verbo NO registra formas de presente en su entrada de la lista irregular?",o:["Be","Do","Go","Have"],c:3,e:"La lista recoge 'Be / am, are, is', 'Do (Does)' y 'Go (Goes)'; 'have' aparece solo con had/had."},
{s:"B",q:"¿Qué serie sigue el patrón vocálico i–a–u en las tres formas?",o:["Drink – Sing – Swim","Sleep – Keep – Feel","Bleed – Lead – Flee","Meet – Feed – Deal"],c:0,e:"Drank/drunk, sang/sung, swam/swum; las demás series conservan la vocal 'e' (slept, kept, felt, bled, led, fled, met, fed, dealt)."},
{s:"B",q:"¿Qué serie sigue el patrón i→u, sin forma intermedia en 'a'?",o:["Sing – Sink – Shrink","Begin – Sit – Spit","Cling – Swing – Wring","Spring – Swim – Drink"],c:2,e:"Clung, swung, wrung; sing/sink/shrink, spring/swim/drink usan i–a–u, y begin → began, sit → sat, spit → spat."},
{s:"B",q:"¿Cuál de estos verbos NO sigue el patrón ow–ew–own de 'throw–threw–thrown'?",o:["Grow","Know","Blow","Draw"],c:3,e:"Draw → drew → drawn (dibujar) usa la vocal 'aw'; grow, know y blow forman grew/grown, knew/known, blew/blown."},
{s:"B",q:"¿Qué serie comparte e→o en el pasado y participio en -n?",o:["Steal – Tear – Find","Speak – Break – Weave","Mean – Deal – Dream","Learn – Spill – Spoil"],c:1,e:"Spoke/spoken, broke/broken, wove/woven; en la opción A, steal y tear cumplen pero find (found, sin -n) rompe el patrón."},
{s:"B",q:"¿Cuál NO pertenece al grupo con pasado y participio en -ought/-aught?",o:["Deal","Seek","Think","Teach"],c:0,e:"Deal → dealt (tratar); sought, thought y taught sí pertenecen al grupo."},
{s:"B",q:"¿Cuál de estos verbos NO forma pasado/participio en -pt?",o:["Sweep","Creep","Bleed","Leap"],c:2,e:"Bleed → bled (sangrar), sin '-t' final; swept, crept y leapt sí la llevan."},
{s:"B",q:"¿Qué serie comparte terminación -ent en pasado y participio?",o:["Lend – Send – Spend","Hold – Hear – Hurt","Make – Take – Shake","Say – Pay – Tell"],c:0,e:"Lent, sent, spent (como bend → bent); held/heard/hurt, made/took/shook y said/paid/told siguen otros patrones."},
{s:"B",q:"¿Qué par de verbos forma el pasado simple en '-aid'?",o:["Tell y Sell","Teach y Buy","Say y Pay","Make y Take"],c:2,e:"Said y paid; tell/sell → told/sold, teach/buy → taught/bought, make/take → made/took."},
{s:"B",q:"¿Qué verbo replica exactamente el patrón de 'give–gave–given'?",o:["Forget","Forgive","Fall","Get"],c:1,e:"Forgive → forgave → forgiven (perdonar); forget → forgot/forgotten, fall → fell/fallen, get → got/got(ten)."},
{s:"B",q:"¿Qué dos verbos figuran a la vez en la lista de irregulares y en la de regulares?",o:["Dream y Burn","Spill y Spoil","Sew y Sow","Show y Learn"],c:3,e:"'Show' aparece como irregular (showed–shown) y regular (showed /d/); 'learn' como irregular (learnt/learned) y regular (learned /d/); los demás solo figuran como irregulares."},
{s:"C",q:"'Shore / shorn' son formas del verbo que significa:",o:["Brillar","Esquilar","Encoger","Soplar"],c:1,e:"Shear → shore → shorn = esquilar; brillar = shine, encogerse = shrink, soplar = blow."},
{s:"C",q:"'Ground / ground' corresponden a:",o:["Moler","Hilar","Torcer","Pegar"],c:0,e:"Grind → ground → ground = moler; hilar = spin, torcer = wring, pegar = stick."},
{s:"C",q:"El verbo 'wring' significa:",o:["Ganar","Escribir","Torcer","Coser"],c:2,e:"Wring → wrung → wrung = torcer; ganar = win, escribir = write, coser = sew."},
{s:"C",q:"'Stride' significa:",o:["Dar zancadas","Saltar","Columpiarse","Resbalar"],c:0,e:"Stride → strode → stridden; saltar = spring, columpiarse = swing, resbalar = slide."},
{s:"C",q:"'Wove / woven' corresponden al verbo que significa:",o:["Llevar puesto","Sembrar","Mojar","Tejer"],c:3,e:"Weave = tejer; llevar puesto = wear, sembrar = sow, mojar = wet."},
{s:"C",q:"'Wept' es pasado de:",o:["Barrer","Llorar","Conservar","Dormir"],c:1,e:"Weep → wept → wept = llorar; barrer = sweep, conservar = keep, dormir = sleep."},
{s:"C",q:"'Knelt' es pasado de:",o:["Arrodillarse","Agarrarse","Colgar","Atar"],c:0,e:"Kneel → knelt → knelt = arrodillarse; agarrarse = cling, colgar = hang, atar = bind."},
{s:"C",q:"'Crept' es pasado de:",o:["Cavar","Acelerar","Arrastrarse","Soplar"],c:2,e:"Creep → crept → crept = arrastrarse; cavar = dig, acelerar = speed, soplar = blow."},
{s:"C",q:"'Bound' es pasado de:",o:["Enviar","Hundir","Encontrar","Atar"],c:3,e:"Bind → bound → bound = atar, encuadernar; enviar = send, hundir = sink, encontrar = find."},
{s:"C",q:"El verbo invariable 'bid' significa:",o:["Apostar","Pujar","Golpear","Disparar"],c:1,e:"Bid (bid/bid) = pujar; apostar = bet (también invariable), golpear = beat, disparar = shoot."},
{s:"C",q:"'Underwent / undergone' corresponden a:",o:["Sufrir","Emprender","Entender","Retirarse"],c:0,e:"Undergo = sufrir; emprender = undertake (undertook/undertaken), entender = understand, retirarse = withdraw."},
{s:"C",q:"'Withdrew / withdrawn' corresponden a:",o:["Vencer","Prohibir","Retirarse","Jurar"],c:2,e:"Withdraw = retirarse; vencer = overcome, prohibir = forbid, jurar = swear."},
{s:"C",q:"El verbo invariable 'split' significa:",o:["Extender","Hender, partir, rajar","Hundir","Torcer"],c:1,e:"Split mantiene sus tres formas; extender = spread, hundir = sink, torcer = wring."},
{s:"C",q:"'Stung' es pasado de:",o:["Apestar","Pegar","Morder","Picar"],c:3,e:"Sting → stung → stung = picar; apestar = stink, pegar = stick, morder = bite."},
{s:"C",q:"El verbo invariable 'thrust' significa:",o:["Introducir","Permitir","Arrojar","Empujar"],c:0,e:"Thrust = introducir; permitir = let, arrojar/tirar = throw, empujar = push (regular /t/)."},
{s:"C",q:"'Bred' es pasado de:",o:["Sangrar","Criar","Crecer","Sembrar"],c:1,e:"Breed → bred → bred = criar; sangrar = bleed, crecer = grow, sembrar = sow."},
{s:"C",q:"El verbo invariable 'burst' significa:",o:["Radiar","Estropear","Reventar","Hinchar"],c:2,e:"Burst = reventar; radiar = broadcast, estropear = spoil, hinchar = swell."},
{s:"D",q:"¿Cuál de estos verbos regulares se pronuncia /Id/ en pasado y participio?",o:["Wash","Need","Walk","Love"],c:1,e:"Need → needed /Id/ (necesitar); wash y walk pertenecen al grupo /t/ y love al /d/."},
{s:"D",q:"¿Cuál pertenece al grupo de pronunciación /t/?",o:["Answer","Enjoy","Clean","Miss"],c:3,e:"Missed /t/ (extrañar); answered, enjoyed y cleaned figuran en el grupo /d/."},
{s:"D",q:"¿Cuál de los siguientes NO figura en el grupo de pronunciación /d/?",o:["Arrive","Climb","Smoke","Follow"],c:2,e:"Smoked /t/ (fumar); arrived, climbed y followed son /d/."},
{s:"D",q:"Según la lista, el pasado de 'use' se clasifica en el grupo:",o:["/Id/","/t/","/d/","/t/ y /d/"],c:1,e:"La lista inscribe 'Use – Used /t/ – Used /t/' dentro del grupo /t/, junto a like, smoke o practice."},
{s:"D",q:"Los verbos del grupo /Id/ (accepted, counted, ended, needed…) comparten la característica de que su infinitivo:",o:["Termina en sonido /t/ o /d/","Duplica la consonante final","Termina en '-y'","Admite formas dobles"],c:0,e:"Accept, count, date, end, expect, intend, need, plant, visit, wait, want… terminan en sonido /t/ o /d/, lo que exige la sílaba adicional /Id/."},
{s:"D",q:"Hurry–hurried, study–studied y try–tried comparten el cambio ortográfico:",o:["Duplicación de la consonante final","Adición del sufijo '-en'","Conversión de 'y' en 'i' antes de '-ed'","Supresión de la vocal final"],c:2,e:"'-y' → '-ied' (con pronunciación /d/); la duplicación corresponde a shop–shopped y stop–stopped."},
{s:"D",q:"¿Qué par de verbos duplica la consonante final al formar el pasado?",o:["Shop y Stop","Clean y Walk","Open y Listen","Like y Use"],c:0,e:"Shopped /t/ y stopped /t/; los demás añaden '-ed' sin duplicación."},
{s:"D",q:"Según la lista, la diferencia entre 'sew' y 'sow' es:",o:["Sew = sembrar; sow = coser","Sew = coser; sow = sembrar","Ambos significan coser","Ambos significan sembrar"],c:1,e:"Sew → sewed → sewed/sewn (coser); sow → sowed → sowed/sown (sembrar): ambos admiten participio doble."},
{s:"D",q:"¿Qué dos verbos de la lista significan 'cerrar'?",o:["Wind y Wring","Sew y Sow","Let y Leave","Shut y Close"],c:3,e:"Shut (irregular e invariable) y close (regular, /d/); let = permitir, leave = dejar."},
{s:"D",q:"El verbo regular 'dare' significa:",o:["Retar","Nombrar","Ordenar","Apurar"],c:0,e:"Dare → dared /d/ = retar; nombrar = name, ordenar = order, apurar/darse prisa = hurry."},
{s:"D",q:"El verbo 'deliver' significa:",o:["Pertenecer","Resistir","Entregar","Cambiar"],c:2,e:"Deliver → delivered /d/ = entregar; pertenecer = belong, resistir = resist, cambiar = change."}
]};